# Generated by Django 3.2.25 on 2025-08-27 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='duration',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления должно быть ≥ 1'), django.core.validators.MaxValueValidator(1440, message='Время приготовления не более 1440 мин.')], verbose_name='Время приготовления (мин.)'),
        ),
    ]
