# Generated by Django 3.2.25 on 2025-08-30 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20250830_0959'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientamount',
            name='ingredient_amount_range_check',
        ),
    ]
