# Generated by Django 3.2.3 on 2025-08-16 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Используется для входа и уведомлений.', max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Пожалуйста, введите своё имя.', max_length=150, validators=[django.core.validators.RegexValidator(message='Допустимы только буквы.', regex='^[^\\W\\d_]+$')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Пожалуйста, введите свою фамилию.', max_length=150, validators=[django.core.validators.RegexValidator(message='Допустимы только буквы.', regex='^[^\\W\\d_]+$')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, help_text='Только латинские буквы, цифры и "_".', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Допустимы только латинские буквы, цифры и символ "_".', regex='^[A-Za-z0-9_]+$')], verbose_name='Имя пользователя'),
        ),
    ]
