# Generated by Django 3.2.3 on 2025-08-16 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250816_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Допустимы только латинские буквы, цифры и символ "_".', regex='^[A-Za-z0-9_]+$')], verbose_name='Имя пользователя'),
        ),
    ]
