# Generated by Django 3.2.3 on 2025-08-16 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Допустимы только буквы.', regex='^[^\\W\\d_]+$')], verbose_name='Имя'),
        ),
    ]
