# Generated by Django 3.2.3 on 2025-08-18 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Допустимы только латинские буквы, цифры и символ "_".', regex='^[A-Za-z0-9_]+$')], verbose_name='Имя пользователя'),
        ),
    ]
