# Generated by Django 3.2.3 on 2025-08-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20250818_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.SlugField(max_length=150, verbose_name='Фамилия'),
        ),
    ]
