# Generated by Django 3.2.25 on 2025-08-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
