# Generated by Django 3.2.25 on 2025-08-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.SlugField(allow_unicode=True, max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
