# Generated by Django 3.2.25 on 2026-01-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20250830_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='', max_length=150, verbose_name='Отчество'),
        ),
    ]
